/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProducaoCientificaRouteImport } from './routes/producao-cientifica'
import { Route as HomenagensRouteImport } from './routes/homenagens'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as CronicasECartasRouteImport } from './routes/cronicas-e-cartas'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BiografiaRouteImport } from './routes/biografia'
import { Route as AulasEPalestrasRouteImport } from './routes/aulas-e-palestras'
import { Route as ArtigosRouteImport } from './routes/artigos'
import { Route as AcervoRouteImport } from './routes/acervo'
import { Route as IndexRouteImport } from './routes/index'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoCientificaRoute = ProducaoCientificaRouteImport.update({
  id: '/producao-cientifica',
  path: '/producao-cientifica',
  getParentRoute: () => rootRouteImport,
} as any)
const HomenagensRoute = HomenagensRouteImport.update({
  id: '/homenagens',
  path: '/homenagens',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const CronicasECartasRoute = CronicasECartasRouteImport.update({
  id: '/cronicas-e-cartas',
  path: '/cronicas-e-cartas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BiografiaRoute = BiografiaRouteImport.update({
  id: '/biografia',
  path: '/biografia',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasEPalestrasRoute = AulasEPalestrasRouteImport.update({
  id: '/aulas-e-palestras',
  path: '/aulas-e-palestras',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosRoute = ArtigosRouteImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => rootRouteImport,
} as any)
const AcervoRoute = AcervoRouteImport.update({
  id: '/acervo',
  path: '/acervo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acervo': typeof AcervoRoute
  '/artigos': typeof ArtigosRoute
  '/aulas-e-palestras': typeof AulasEPalestrasRoute
  '/biografia': typeof BiografiaRoute
  '/contato': typeof ContatoRoute
  '/cronicas-e-cartas': typeof CronicasECartasRoute
  '/galeria': typeof GaleriaRoute
  '/homenagens': typeof HomenagensRoute
  '/producao-cientifica': typeof ProducaoCientificaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acervo': typeof AcervoRoute
  '/artigos': typeof ArtigosRoute
  '/aulas-e-palestras': typeof AulasEPalestrasRoute
  '/biografia': typeof BiografiaRoute
  '/contato': typeof ContatoRoute
  '/cronicas-e-cartas': typeof CronicasECartasRoute
  '/galeria': typeof GaleriaRoute
  '/homenagens': typeof HomenagensRoute
  '/producao-cientifica': typeof ProducaoCientificaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acervo': typeof AcervoRoute
  '/artigos': typeof ArtigosRoute
  '/aulas-e-palestras': typeof AulasEPalestrasRoute
  '/biografia': typeof BiografiaRoute
  '/contato': typeof ContatoRoute
  '/cronicas-e-cartas': typeof CronicasECartasRoute
  '/galeria': typeof GaleriaRoute
  '/homenagens': typeof HomenagensRoute
  '/producao-cientifica': typeof ProducaoCientificaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acervo'
    | '/artigos'
    | '/aulas-e-palestras'
    | '/biografia'
    | '/contato'
    | '/cronicas-e-cartas'
    | '/galeria'
    | '/homenagens'
    | '/producao-cientifica'
    | '/sitemap.xml'
    | '/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acervo'
    | '/artigos'
    | '/aulas-e-palestras'
    | '/biografia'
    | '/contato'
    | '/cronicas-e-cartas'
    | '/galeria'
    | '/homenagens'
    | '/producao-cientifica'
    | '/sitemap.xml'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/acervo'
    | '/artigos'
    | '/aulas-e-palestras'
    | '/biografia'
    | '/contato'
    | '/cronicas-e-cartas'
    | '/galeria'
    | '/homenagens'
    | '/producao-cientifica'
    | '/sitemap.xml'
    | '/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcervoRoute: typeof AcervoRoute
  ArtigosRoute: typeof ArtigosRoute
  AulasEPalestrasRoute: typeof AulasEPalestrasRoute
  BiografiaRoute: typeof BiografiaRoute
  ContatoRoute: typeof ContatoRoute
  CronicasECartasRoute: typeof CronicasECartasRoute
  GaleriaRoute: typeof GaleriaRoute
  HomenagensRoute: typeof HomenagensRoute
  ProducaoCientificaRoute: typeof ProducaoCientificaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao-cientifica': {
      id: '/producao-cientifica'
      path: '/producao-cientifica'
      fullPath: '/producao-cientifica'
      preLoaderRoute: typeof ProducaoCientificaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homenagens': {
      id: '/homenagens'
      path: '/homenagens'
      fullPath: '/homenagens'
      preLoaderRoute: typeof HomenagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronicas-e-cartas': {
      id: '/cronicas-e-cartas'
      path: '/cronicas-e-cartas'
      fullPath: '/cronicas-e-cartas'
      preLoaderRoute: typeof CronicasECartasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biografia': {
      id: '/biografia'
      path: '/biografia'
      fullPath: '/biografia'
      preLoaderRoute: typeof BiografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas-e-palestras': {
      id: '/aulas-e-palestras'
      path: '/aulas-e-palestras'
      fullPath: '/aulas-e-palestras'
      preLoaderRoute: typeof AulasEPalestrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos': {
      id: '/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof ArtigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acervo': {
      id: '/acervo'
      path: '/acervo'
      fullPath: '/acervo'
      preLoaderRoute: typeof AcervoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcervoRoute: AcervoRoute,
  ArtigosRoute: ArtigosRoute,
  AulasEPalestrasRoute: AulasEPalestrasRoute,
  BiografiaRoute: BiografiaRoute,
  ContatoRoute: ContatoRoute,
  CronicasECartasRoute: CronicasECartasRoute,
  GaleriaRoute: GaleriaRoute,
  HomenagensRoute: HomenagensRoute,
  ProducaoCientificaRoute: ProducaoCientificaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
